/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.summercoding.bank.ui;

import com.summercoding.bank.controlleur.Controlleur;
import com.summercoding.bank.entities.Admin;
import com.summercoding.bank.entities.Compte;
import com.summercoding.bank.entities.Utilisateur;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TCHAWA Dickens
 */
public class JFrameHome extends javax.swing.JFrame {

    Controlleur controlleur = new Controlleur();
    JFrameSaveAdmin saveadmin = new JFrameSaveAdmin();
    JFrameSaveUtilisateur saveuser = new JFrameSaveUtilisateur();
    JFrameSaveCompte savecompte = new JFrameSaveCompte();

    /**
     * Creates new form JFrameHome
     */
    public JFrameHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HomeTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuCreerAdmin = new javax.swing.JMenuItem();
        MenuListerAdmin = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuCreerUtilisateur = new javax.swing.JMenuItem();
        MenuListerUtilisateur = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        MenuCreerCompte = new javax.swing.JMenuItem();
        MenuListerCompte = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu9.setText("File");
        jMenuBar2.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar2.add(jMenu10);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HomeMenu");

        HomeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(HomeTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
        );

        jMenu1.setText("Admin");

        MenuCreerAdmin.setText("Créer");
        MenuCreerAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCreerAdminActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCreerAdmin);

        MenuListerAdmin.setText("Liste");
        MenuListerAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuListerAdminActionPerformed(evt);
            }
        });
        jMenu1.add(MenuListerAdmin);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Utilisateur");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        MenuCreerUtilisateur.setText("Créer");
        MenuCreerUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCreerUtilisateurActionPerformed(evt);
            }
        });
        jMenu2.add(MenuCreerUtilisateur);

        MenuListerUtilisateur.setText("Liste");
        MenuListerUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuListerUtilisateurActionPerformed(evt);
            }
        });
        jMenu2.add(MenuListerUtilisateur);

        jMenuBar1.add(jMenu2);

        jMenu11.setText("Compte");

        MenuCreerCompte.setText("Créer");
        MenuCreerCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCreerCompteActionPerformed(evt);
            }
        });
        jMenu11.add(MenuCreerCompte);

        MenuListerCompte.setText("Liste");
        MenuListerCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuListerCompteActionPerformed(evt);
            }
        });
        jMenu11.add(MenuListerCompte);

        jMenuBar1.add(jMenu11);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCreerAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCreerAdminActionPerformed
        // TODO add your handling code here:
        saveadmin.setVisible(true);
    }//GEN-LAST:event_MenuCreerAdminActionPerformed

    private void MenuCreerUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCreerUtilisateurActionPerformed
        // TODO add your handling code here:
        saveuser.setVisible(true);
    }//GEN-LAST:event_MenuCreerUtilisateurActionPerformed

    private void MenuCreerCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCreerCompteActionPerformed
        // TODO add your handling code here:
        savecompte.setVisible(true);
    }//GEN-LAST:event_MenuCreerCompteActionPerformed

    private void MenuListerAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuListerAdminActionPerformed
        try {
            // TODO add your handling code here:
            /* String[] columns = new String [] {
             "Id","Nom","Login"
             };
            
             Object[][] datas = new Object [][] {
             {"1","toto","toto"},
             {"2","tata","tata"},
             {"3","titi","titi"},
             {"4","tutu","tutu"}
            
             }; */

            List<Admin> listAdmin = controlleur.routeVersListAllAdmin();

            DefaultTableModel model = (DefaultTableModel) HomeTable.getModel();
            model.addColumn("id");
            model.addColumn("Nom");
            model.addColumn("Login");

            for (Admin ad : listAdmin) {
                model.addRow(new String[]{ad.getIdadmin() + "", ad.getNom() + "", ad.getLogin()});
            }

            HomeTable.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(JFrameHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MenuListerAdminActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void MenuListerUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuListerUtilisateurActionPerformed
        try {
            // TODO add your handling code here:
            List<Utilisateur> listUser = controlleur.routeVersListeUtilisateur();

            DefaultTableModel model0 = (DefaultTableModel) HomeTable.getModel();
            model0.addColumn("Id User");
            model0.addColumn("Login");
            model0.addColumn("Nom");
            model0.addColumn("Prenom");
            model0.addColumn("Datenaiss");
            model0.addColumn("Genre");
            model0.addColumn("Id Admin");

            for (Utilisateur ad : listUser) {
                model0.addRow(new Object[]{ad.getIduser() + "", ad.getLogin() + "", ad.getNom() + "", ad.getPrenom() + "", ad.getDatenaiss() + "", ad.getGenre() + "", ad.getIdadmin()});
            }

            HomeTable.setModel(model0);
        } catch (SQLException ex) {
            Logger.getLogger(JFrameHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MenuListerUtilisateurActionPerformed

    private void MenuListerCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuListerCompteActionPerformed
        try {
            // TODO add your handling code here:
            List<Compte> listCompte = controlleur.routeVersListeCompte();
            
            DefaultTableModel model1 = (DefaultTableModel) HomeTable.getModel();
            model1.addColumn("Id");
            model1.addColumn("Solde");
            model1.addColumn("Id Admin");
            model1.addColumn("Id User");

            for (Compte ad : listCompte) {
                model1.addRow(new Object[]{ad.getIdcompte()+ "", ad.getSolde()+"", ad.getIdadmin()+"", ad.getIduser()});
            }

            HomeTable.setModel(model1);
        } catch (SQLException ex) {
            Logger.getLogger(JFrameHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MenuListerCompteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable HomeTable;
    private javax.swing.JMenuItem MenuCreerAdmin;
    private javax.swing.JMenuItem MenuCreerCompte;
    private javax.swing.JMenuItem MenuCreerUtilisateur;
    private javax.swing.JMenuItem MenuListerAdmin;
    private javax.swing.JMenuItem MenuListerCompte;
    private javax.swing.JMenuItem MenuListerUtilisateur;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
